### ISSUE TITLE
about Disparity range 

### ISSUE THREAD

**Issue by ksh11023** [ZM-Zhou/SDFA-Net_pytorch#2]
Hello,

Is there specific reason for setting the disparity range [2, 300] ? 
Can SDFA-net be trained with disparity range [0,192] ? 

Thank you!

**Comment by ZM-Zhou** [comment]
Hi ksh11023,

We follow the existing work (FAL-Net) to set the disparity range [2, 300]. Of course, you could try to set different disparity ranges in your training (by modifying the yaml file). Please note that the min_disp should not be set as 0, as it would cause a numerical error during depth computing.

**Comment by ksh11023** [comment]
Thank you for the reply !
