### ISSUE TITLE
 KITTI results on 192X640

### ISSUE THREAD

**Issue by ksh11023** [ZM-Zhou/SDFA-Net_pytorch#5]
Hello,

Do you have KITTI test result for resolution 192X640 ? 

Thank you

**Comment by ZM-Zhou** [comment]
Hi ksh11023,

We have not trained the SDFA-Net for resolution 192x640. We will add this model in the future.

**Comment by sungheuiK** [comment]
Hello,

 'We have not trained the SDFA-Net for resolution 192x640' <- does this mean you have only trained image with (384x1280) without cropping the image?

**Comment by ksh11023** [comment]
@ZM-Zhou

Hello,

'We have not trained the SDFA-Net for resolution 192x640' <- does this mean you have only trained image with (384x1280) without cropping the image?

**Comment by ksh11023** [comment]
@ZM-Zhou

Does random cropping affects a lot in producing the result?
Is it okay to do the random cropping with any size keeping the ratio of (384x1280)?
