### ISSUE TITLE
About the reproduction

### ISSUE THREAD

**Issue by sungheuiK** [ZM-Zhou/SDFA-Net_pytorch#6]
Hello!

I have a question regarding the results on the paper (Table 1).  Does these results imply that the model is trained without cropping the image into (192 x 640) ? So, if I want to reproduce the results on the paper, I have to change train_384rc.yaml and set the patch size to None ?

Thank you

**Comment by ZM-Zhou** [comment]
Hi,
Thanks for your attention!
The results in Table 1 of the paper were generated with the training settings in this repo, and random cropping was enabled in all the experiments.

**Comment by sungheuiK** [comment]
okay, thank you
