### ISSUE TITLE
download pretrained model 

### ISSUE THREAD

**Issue by ksh11023** [ZM-Zhou/SDFA-Net_pytorch#9]
I cannot download pretrained model.
Can you please check if 'SDFA-Net-SwinTM_384' is able to download?

![Screenshot from 2022-11-16 20-59-03](https://user-images.githubusercontent.com/50094436/202175197-f2b52b4f-2097-403d-aa9e-558140642dc9.png)

After selecting this option

![Screenshot from 2022-11-16 20-57-03](https://user-images.githubusercontent.com/50094436/202175261-43fc42bb-1ce4-417c-863e-6868d4939b9d.png)

This goes over and over.

Thank you

**Comment by ZM-Zhou** [comment]
Hi 
I think it works well on Windows, but I have not tried to download it on Linux. There may be something wrong with PanBaidu on Linux.
I am uploading the pre-trained model to google drive, I hope it would be helpful.

**Comment by ksh11023** [comment]
Thank you, that would be great!

**Comment by ksh11023** [comment]
Thank you:)
